PRODUCT_VERSION_MAJOR = 12
PRODUCT_VERSION_MINOR = 1

# Rice Version
RICE_VERSION := HaloHalo
RICE_CODE := 5.0
RICE_FLAVOR := Sizzle
RICE_DEVICE := $(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)

# build type
ifeq ($(RICE_OFFICIAL),true)
RICE_BUILD_TYPE := OFFICIAL
else
RICE_BUILD_TYPE := COMMUNITY
endif

ifeq ($(WITH_GMS),true)
PACKAGE_BUILD_TYPE := PIXEL
else
PACKAGE_BUILD_TYPE := VANILLA
endif

# Internal version
ifeq ($(WITH_GMS),true)
LINEAGE_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d%H)-$(RICE_DEVICE)-v$(RICE_CODE)-PIXEL
else
LINEAGE_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d%H)-$(RICE_DEVICE)-v$(RICE_CODE)-VANILLA
endif
# Display version
LINEAGE_DISPLAY_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(RICE_DEVICE)-v$(RICE_CODE)
