PRODUCT_VERSION_MAJOR = 12
PRODUCT_VERSION_MINOR = 1

# Rice Version
RICE_VERSION = Adobo
RICE_CODE := 1.0
RICE_FLAVOR := Sizzle
RICE_DEVICE ?= 3310

# build type
RICE_BUILD_TYPE ?= OFFICIAL

ifeq ($(WITH_GAPPS),true)
PACKAGE_BUILD_TYPE ?= GAPPS
else
PACKAGE_BUILD_TYPE ?= VANILLA
endif

# Internal version
ifeq ($(WITH_GAPPS),true)
LINEAGE_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d%H%M)-$(RICE_DEVICE)-v$(RICE_CODE)-GAPPS
else
LINEAGE_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d%H%M)-$(RICE_DEVICE)-v$(RICE_CODE)-VANILLA-$(shell date +%Y%m)
endif
# Display version
LINEAGE_DISPLAY_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(RICE_DEVICE)-v$(RICE_CODE)
