PRODUCT_VERSION_MAJOR = 12
PRODUCT_VERSION_MINOR = 1

# Rice Version
RICE_VERSION := Calamares
RICE_CODE := 2.0
RICE_FLAVOR := Sizzle
RICE_DEVICE ?= 3310

# build type
ifeq ($(RICE_OFFICIAL),true)
RICE_BUILD_TYPE := OFFICIAL
else
RICE_BUILD_TYPE := COMMUNITY
endif

ifeq ($(WITH_GAPPS),true)
PACKAGE_BUILD_TYPE := GAPPS
else
PACKAGE_BUILD_TYPE := VANILLA
endif

# Internal version
ifeq ($(WITH_GAPPS),true)
LINEAGE_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d%H%M)-$(RICE_DEVICE)-v$(RICE_CODE)-GAPPS
else
LINEAGE_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d%H%M)-$(RICE_DEVICE)-v$(RICE_CODE)-VANILLA
endif
# Display version
LINEAGE_DISPLAY_VERSION := riceDroid-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(RICE_DEVICE)-v$(RICE_CODE)
